CREATE DATABASE IF NOT EXIST hierarchydb;

USE hierarchydb;

DROP TABLE IF EXISTS products;

CREATE TABLE products (
 parentId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 name VARCHAR(255) DEFAULT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (parentId)
);


-- DROP TABLE IS EXISTS children;

-- CREATE TABLE children (
--  childId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--  name VARCHAR(255) DEFAULT NULL,
--  height NUMBER NOT NULL,
--  parent VARCHAR(255) DEFAULT NULL,
--  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--  PRIMARY KEY(childId),
--  FOREIGN KEY (parentId) REFERENCES parent(parentId)
-- );

